use ouro_index_vec::IndexVec;
use ouro_span::{Byte, Span, Unit};
use std::fmt::Debug;

ouro_index_vec::define_index_type! {
    pub struct Token = u32;
}

#[derive(Debug)]
pub struct Tokenize {
    pub tokens: IndexVec<Token, TokenImpl>,
    pub spans: ByteSpans,
}

#[derive(Debug)]
pub struct Spans<U: Unit> {
    pub ends: IndexVec<Token, U>,
}

pub type ByteSpans = Spans<Byte>;

impl<U: Unit> Spans<U> {
    pub fn start(&self, token: Token) -> U {
        if token.index() == 0 {
            U::from(0)
        } else {
            self.ends[token - 1]
        }
    }

    pub fn to_span(&self, token: Token) -> Span<U> {
        Span {
            start: self.start(token),
            end: self.ends[token],
        }
    }
}

/// Token types.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum TokenImpl {
    /// Integers, or anything that might look like one.
    IntLit,
    /// Identifiers.
    Ident,
    /// Strings like `"hello world"`.
    StrLit,
    /// Generated by [`Tokenizer`].
    UnterminatedStrLit,
    /// Fully escaped raw string.
    RawStrLit,

    // Symbols
    OpenBrace,
    CloseBrace,
    OpenParen,
    CloseParen,
    Dot,
    Comma,
    Colon,
    Semi,
    Plus,
    Dash,
    Star,
    Slash,
    Eq,
    EqEq,
    RArrow,
    Bang,
    Ampersand,

    // Keywords
    Pub,
    True,
    False,
    Let,
    Const,
    Fn,
    Struct,
    Comptime,
    If,
    Else,

    // Builtin values
    I32Keyword,
    TypeKeyword,

    // Other
    Comment,
    Newline,
    Whitespace,

    Unrecognized,
}
