[package]
name = "ouro_resolve"
version = "0.0.0"
edition = "2024"

[lib]
path = "ouro_resolve.rs"

[[test]]
name = "ouro_resolve_test"
path = "ouro_resolve_test.rs"

[dependencies]
ouro_index_vec = { path = "../ouro_index_vec" }
ouro_tokenize_types = { path = "../ouro_tokenize_types" }
ouro_parse_types = { path = "../ouro_parse_types" }

[dev-dependencies]
insta = { workspace = true }
ouro_tokenize = { path = "../ouro_tokenize" }
ouro_parse = { path = "../ouro_parse" }
