[package]
name = "ouro_tokenize"
version = "0.0.0"
edition = "2024"

[lib]
path = "ouro_tokenize.rs"

[[test]]
name = "ouro_tokenize_test"
path = "ouro_tokenize_test.rs"

[dependencies]
ouro_index_vec = { path = "../ouro_index_vec" }
ouro_span = { path = "../ouro_span" }
logos = "0.16.1"

[dev-dependencies]
insta = { workspace = true }
