use logos::{Lexer, Logos};
use ouro_index_vec::{IndexSlice, IndexVec};
use ouro_span::{Byte, Span, Unit};
use std::fmt::Debug;

ouro_index_vec::define_index_type! {
    pub struct Token = u32;
}

/// Moves the lexer to the end of the string or the end of the line, whichever comes first.
fn tokenize_string(lexer: &mut Lexer<'_, TokenImpl>) -> Result<(), Error> {
    let s = lexer.remainder();

    let mut escaped = false;
    for (offset, byte) in s.bytes().enumerate() {
        if byte == b'\n' {
            lexer.bump(offset);
            return Err(Error::UnterminatedStr);
        }

        if escaped {
            escaped = false;
            continue;
        }

        if byte == b'"' {
            lexer.bump(offset + 1);
            return Ok(());
        }

        if byte == b'\\' {
            escaped = true;
        }
    }

    lexer.bump(s.len());
    Err(Error::UnterminatedStr)
}

fn advance_to_end_of_line(lexer: &mut Lexer<'_, TokenImpl>) {
    let s = lexer.remainder();

    for (offset, byte) in s.bytes().enumerate() {
        if byte == b'\n' {
            lexer.bump(offset);
            return;
        }
    }

    lexer.bump(s.len());
}

#[derive(Copy, Clone, Debug, Default, PartialEq, Eq, Hash)]
pub enum Error {
    UnterminatedStr,
    #[default]
    Unrecognized,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, Logos)]
#[logos(error = Error)]
pub enum TokenImpl {
    /// Integers, or anything that might look like one.
    #[regex("[0-9][a-zA-Z0-9_]*", priority = 3)]
    Int,
    /// Identifiers.
    #[regex(r"\w+")]
    Ident,
    /// Strings like `"hello world"`.
    #[token("\"", tokenize_string)]
    Str,
    /// Generated by [`Tokenizer`].
    UnterminatedStr,
    /// Fully escaped raw string.
    #[token("\\\\", advance_to_end_of_line)]
    RawStr,

    // Symbols
    #[token("{")]
    OpenBrace,
    #[token("}")]
    CloseBrace,
    #[token("(")]
    OpenParen,
    #[token(")")]
    CloseParen,
    #[token(".")]
    Dot,
    #[token(",")]
    Comma,
    #[token(":")]
    Colon,
    #[token(";")]
    Semi,
    #[token("+")]
    Plus,
    #[token("-")]
    Dash,
    #[token("*")]
    Star,
    #[token("/")]
    Slash,
    #[token("=")]
    Eq,
    #[token("==")]
    EqEq,
    #[token("->")]
    RArrow,
    #[token("!")]
    Bang,

    // Keywords
    #[token("pub")]
    Pub,
    #[token("true")]
    True,
    #[token("false")]
    False,
    #[token("let")]
    Let,
    #[token("const")]
    Const,
    #[token("fn")]
    Fn,
    #[token("struct")]
    Struct,
    #[token("comptime")]
    Comptime,
    #[token("if")]
    If,
    #[token("else")]
    Else,

    // Other
    #[token("//", advance_to_end_of_line)]
    Comment,
    #[token("\n")]
    Newline,
    #[regex(r"[ \t\r\f]+")]
    Whitespace,

    Unrecognized,
}

/// The lexer for [`Token`]s.
#[derive(Clone, Debug)]
pub struct Tokenizer<'input> {
    lexer: Lexer<'input, TokenImpl>,
}

impl<'input> Tokenizer<'input> {
    /// Returns a new [`Tokenizer<'_>`].
    pub fn new(source: &'input str) -> Self {
        Tokenizer {
            lexer: TokenImpl::lexer(source),
        }
    }

    pub fn lexer(&self) -> &Lexer<'input, TokenImpl> {
        &self.lexer
    }
}

impl<'source> Iterator for Tokenizer<'source> {
    type Item = TokenImpl;

    fn next(&mut self) -> Option<Self::Item> {
        match self.lexer.next()? {
            Ok(token) => Some(token),
            Err(Error::UnterminatedStr) => Some(TokenImpl::UnterminatedStr),
            Err(Error::Unrecognized) => Some(TokenImpl::Unrecognized),
        }
    }
}

#[derive(Debug)]
pub struct Tokenize {
    pub tokens: IndexVec<Token, TokenImpl>,
    pub ends: IndexVec<Token, Byte>,
}

/// Returns a vector of tokens and their corresponding end offsets. Every byte in the input corresponds to a token,
/// so the end offsets are 1 past the end of each token.
pub fn tokenize(input: &str) -> Tokenize {
    let mut tokenizer = Tokenizer::new(input);
    let mut tokens = IndexVec::new();
    let mut ends = IndexVec::new();

    while let Some(token_impl) = tokenizer.next() {
        tokens.push(token_impl);
        ends.push(Byte::from_usize(tokenizer.lexer().span().end));
    }

    Tokenize { tokens, ends }
}

pub fn start<U: Unit>(token: Token, ends: &IndexSlice<Token, [U]>) -> U {
    if token.index() == 0 {
        U::from(0)
    } else {
        ends[token - 1]
    }
}

pub fn span<U: Unit>(token: Token, ends: &IndexSlice<Token, [U]>) -> Span<U> {
    Span {
        start: start(token, ends),
        end: ends[token],
    }
}
