[package]
name = "ouro_parse_types"
version = "0.0.0"
edition = "2024"

[lib]
path = "ouro_parse_types.rs"

[dependencies]
ouro_index_vec = { path = "../ouro_index_vec" }
ouro_span = { path = "../ouro_span" }
ouro_tokenize_types = { path = "../ouro_tokenize_types" }

[dev-dependencies]
insta = { workspace = true }
