use crate::span::{Offset, Span};
use index_vec::{IndexSlice, IndexVec};
use logos::{Lexer, Logos};
use std::fmt::Debug;

index_vec::define_index_type! {
    pub struct Token = u32;
}

fn on_newline(lexer: &mut Lexer<'_, TokenImpl>) {
    lexer.extras.current_line.line_number += 1;
    lexer.extras.current_line.line_byte_offset = lexer.span().end;
}

/// Moves the lexer to the end of the string or the end of the line, whichever comes first.
fn tokenize_string(lexer: &mut Lexer<'_, TokenImpl>) -> Result<(), Error> {
    let s = lexer.remainder();

    let mut escaped = false;
    for (offset, byte) in s.bytes().enumerate() {
        if byte == b'\n' {
            lexer.bump(offset);
            return Err(Error::UnterminatedStr);
        }

        if escaped {
            escaped = false;
            continue;
        }

        if byte == b'"' {
            lexer.bump(offset + 1);
            return Ok(());
        }

        if byte == b'\\' {
            escaped = true;
        }
    }

    lexer.bump(s.len());
    Err(Error::UnterminatedStr)
}

fn advance_to_end_of_line(lexer: &mut Lexer<'_, TokenImpl>) {
    let s = lexer.remainder();

    for (offset, byte) in s.bytes().enumerate() {
        if byte == b'\n' {
            lexer.bump(offset);
            return;
        }
    }

    lexer.bump(s.len());
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
struct CurrentLine {
    line_number: usize,
    line_byte_offset: usize,
}

#[doc(hidden)]
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct Extras {
    current_line: CurrentLine,
}

#[derive(Copy, Clone, Debug, Default, PartialEq, Eq, Hash)]
pub enum Error {
    UnterminatedStr,
    #[default]
    Unrecognized,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, Logos)]
#[logos(error = Error)]
#[logos(extras = Extras)]
pub enum TokenImpl {
    /// Integers, or anything that might look like one.
    #[regex("[0-9][a-zA-Z0-9_]*", priority = 3)]
    Int,
    /// Identifiers.
    #[regex(r"\w+")]
    Ident,
    /// Strings like `"hello world"`.
    #[token("\"", tokenize_string)]
    Str,
    /// Generated by [`Tokens`].
    UnterminatedStr,
    /// Fully escaped raw string.
    #[token("\\\\", advance_to_end_of_line)]
    RawStr,

    // Symbols
    #[token("{")]
    OpenBrace,
    #[token("}")]
    CloseBrace,
    #[token("(")]
    OpenParen,
    #[token(")")]
    CloseParen,
    #[token(".")]
    Dot,
    #[token(",")]
    Comma,
    #[token(":")]
    Colon,
    #[token(";")]
    Semi,
    #[token("+")]
    Plus,
    #[token("-")]
    Dash,
    #[token("*")]
    Star,
    #[token("/")]
    Slash,
    #[token("=")]
    Eq,
    #[token("==")]
    EqEq,
    #[token("->")]
    RArrow,
    #[token("!")]
    Bang,

    // Keywords
    #[token("pub")]
    Pub,
    #[token("true")]
    True,
    #[token("false")]
    False,
    #[token("let")]
    Let,
    #[token("const")]
    Const,
    #[token("fn")]
    Fn,
    #[token("struct")]
    Struct,
    #[token("comptime")]
    Comptime,
    #[token("if")]
    If,
    #[token("else")]
    Else,

    // Other
    #[token("//", advance_to_end_of_line)]
    Comment,
    #[token("\n", on_newline)]
    Newline,
    #[regex(r"[ \t\r\f]+")]
    Whitespace,

    Unrecognized,
}

/// The lexer for [`Token`]s.
#[derive(Clone, Debug)]
pub struct Tokenizer<'input> {
    lexer: Lexer<'input, TokenImpl>,
}

impl<'input> Tokenizer<'input> {
    /// Returns a new [`Tokenizer<'_>`].
    pub fn new(source: &'input str) -> Self {
        Tokenizer {
            lexer: TokenImpl::lexer_with_extras(
                source,
                Extras {
                    current_line: CurrentLine {
                        line_number: 1,
                        line_byte_offset: 0,
                    },
                },
            ),
        }
    }

    /// Returns the line and column of the start of the current token.
    ///
    /// Lines start at 1.
    pub fn line_col(&self) -> (usize, usize) {
        let token_offset = self.lexer.span().start;
        let CurrentLine {
            line_number,
            line_byte_offset,
        } = self.lexer.extras.current_line;
        let col = token_offset - line_byte_offset;
        (line_number, col)
    }

    pub fn lexer(&self) -> &Lexer<'input, TokenImpl> {
        &self.lexer
    }
}

impl<'source> Iterator for Tokenizer<'source> {
    type Item = TokenImpl;

    fn next(&mut self) -> Option<Self::Item> {
        match self.lexer.next()? {
            Ok(token) => Some(token),
            Err(Error::UnterminatedStr) => Some(TokenImpl::UnterminatedStr),
            Err(Error::Unrecognized) => Some(TokenImpl::Unrecognized),
        }
    }
}

pub struct Tokenize {
    pub tokens: Box<IndexSlice<Token, [TokenImpl]>>,
    pub ends: Box<IndexSlice<Token, [Offset]>>,
}

/// Returns a vector of tokens and their corresponding end offsets. Every byte in the input corresponds to a token,
/// so the end offsets are 1 past the end of each token.
pub fn tokenize(input: &str) -> Tokenize {
    let mut tokenizer = Tokenizer::new(input);
    let mut tokens = IndexVec::new();
    let mut ends = IndexVec::new();

    while let Some(token) = tokenizer.next() {
        tokens.push(token);
        ends.push(Offset(tokenizer.lexer().span().end as u32));
    }

    Tokenize {
        tokens: tokens.into_boxed_slice(),
        ends: ends.into_boxed_slice(),
    }
}

pub fn span(token: Token, ends: &IndexSlice<Token, [Offset]>) -> Span {
    Span {
        start: if token.index() == 0 {
            Offset(0)
        } else {
            ends[token - 1]
        },
        end: ends[token],
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::span::{Offset, Span};

    fn pprint_tokenize(input: &str) -> String {
        let tokenize = tokenize(input);
        let mut prev = Offset(0);
        let mut output = String::new();

        for (token, end) in tokenize.tokens.iter().zip(tokenize.ends.iter()) {
            use std::fmt::Write;
            writeln!(
                &mut output,
                "{:?} {:?} ",
                token,
                Span {
                    start: prev,
                    end: *end
                }
            )
            .expect("writing to a String cannot fail");
            prev = *end;
        }

        output
    }

    #[test]
    fn t() {
        insta::assert_snapshot!(pprint_tokenize("fn f(x) { 4 + 3 * x } "));
        insta::assert_snapshot!(pprint_tokenize("a *= b;"));
        insta::assert_snapshot!(pprint_tokenize("a *"));
        assert_eq!('😎'.len_utf8(), 4);
        insta::assert_snapshot!(pprint_tokenize("a * 😎"));
        insta::assert_snapshot!(pprint_tokenize("a 1_000_000 123 _123"));
        insta::assert_snapshot!(pprint_tokenize("123😎"));
    }

    #[test]
    fn valid_binary_numbers() {
        insta::assert_snapshot!(pprint_tokenize("0b1010"));
        insta::assert_snapshot!(pprint_tokenize("0b1010_1010"));
        insta::assert_snapshot!(pprint_tokenize("0b0"));
        insta::assert_snapshot!(pprint_tokenize("0b_0"));
    }

    #[test]
    fn invalid_binary_numbers() {
        insta::assert_snapshot!(pprint_tokenize("0b"));
        insta::assert_snapshot!(pprint_tokenize("0b_"));
        insta::assert_snapshot!(pprint_tokenize("0b2"));
        insta::assert_snapshot!(pprint_tokenize("0b_2"));
        insta::assert_snapshot!(pprint_tokenize("0b101a"));
    }

    #[test]
    fn newline_terminated_strings() {
        insta::assert_snapshot!(pprint_tokenize(r"\\Hello, world!"));
        insta::assert_snapshot!(pprint_tokenize(
            r"
            \\Hello, world!
            \\123 123\\
            "
        ));
    }

    #[test]
    fn keywords() {
        insta::assert_snapshot!(pprint_tokenize("let fn comptime"));
        insta::assert_snapshot!(pprint_tokenize("letter fn_ comptime_"));
    }
}
